<?php

namespace pantera\crm\contacts\components\grid;


use kartik\select2\Select2;
use pantera\crm\contacts\models\Contact;
use pantera\crm\contacts\models\Param;
use yii\grid\Column;
use yii\grid\DataColumn;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

class TagsGridColumn extends DataColumn {


    public $filter;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }



    public function renderDataCellContent($model, $key, $index)
    {
        /**
         * @var Contact $model
         */
        parent::renderDataCellContent($model, $key, $index); // TODO: Change the autogenerated stubs;

        $tags = [];

        foreach ($model->tagsRelation as $tag) {
            $tags[] = Html::tag('span', $tag->groupAndName, ['class' => 'label label-default']);
        }

        return implode(' ', $tags);
    }
}
